### ISSUE TITLE
Floats instead of CGFloat

### ISSUE THREAD

**Issue by alexpopov** [floriankrueger/Manuscript#1]
Regular constraints use CGFloats, whereas yours use Floats, and the two are not interchangeable because of type safety. Is there any way, other than redefining my variables, that I can use this class? Our designer uses an 8-point grid, and I have a constant called 'margin' defined at the top level `as CGFloat` 

otherwise love the library

**Comment by floriankrueger** [comment]
Thank you for your issue. You're right, using `Float` instead of `CGFloat` is a controversial decision that I made right at the start of AutoLayoutKit for Swift. 

The thing is that the following code doesn't compile:

``` swift
// view setup, just for reference
let parentView = UIView(frame: CGRectZero)
let childView = UIView(frame: CGRectZero)
parentView.addSubview(childView)

let margin = 4.0
let type = margin.dynamicType // Swift.Double

// doesn't compile
NSLayoutConstraint(item: childView, attribute: .Left, relatedBy: .Equal, toItem: parentView, attribute: .Left, multiplier: 1.0, constant: margin)
```

The compiler says `Could not find member '.Left'` but that's just because type inference is messed up due to `margin` being a `Swift.Double` instead of a `CGFloat`.

One fix is to add the type explicitly to `margin`:

``` swift
let margin:CGFloat = 4.0
let type = margin.dynamicType // CoreGraphics.CGFloat

// compiles. CGFloat(margin) in this call would have worked as well.
NSLayoutConstraint(item: childView, attribute: .Left, relatedBy: .Equal, toItem: parentView, attribute: .Left, multiplier: 1.0, constant: margin)
```

So my first solution to this problem was to 'fix' this in Manuscripts API by using `Float` instead of `CGFloat`, which is obviously wrong because it doesn't match the Swift default floating point type and it doesn't match the `NSLayoutConstraint` floating point type as well.

But when I think about changing the type (which will most likely break the API, which is OK as long as we're below 1.0.0) I'm not quite sure which path to take. CGFloat is stored as a `Double` internally anyways and always having to declare `CGFloat` isn't really pleasant.

Would you care to discuss this with me? I'm open for your thoughts.

**Comment by alexpopov** [comment]
Thanks for the response Florian,

I think switching it to CGFloat is important, since that’s the unit used all across the UI. However, it’s not a huge pain to just set up `let fMargin = Float(margin)` and use the so called float-margin from there on in the class. 

Also, you’re not entirely correct that a CGFloat is a Double internally, it’s architecture specific: on 32-bit phones (i.e. iPhone 5 and below, which we unfortunately still have to support) a CGFloat is represented as a float, whereas on 64-bit devices it is a Double, since that’s the native word-size. Whether or not this plays into Manuscript, I’m not certain. 

It would be a pain to have to refactor the library in terms of CGFloats, but ultimately I think it would only be tedious, not technically challenging. 

—
Alex Popov Jr.Lead Mobile Developer @ BitLit

**Comment by floriankrueger** [comment]
You're welcome. Thank you for the quick response. 

I got your point. Forgot about the 'old' devices a bit - sorry about that ^^ I'll refactor the code and push it on a separate branch  in a bit as it's really not a great deal. And it doesn't make any difference for Manuscript. The library ultimately generates `NSLayoutConstraint` instances like we would do manually without the wrapper. As it says on the box: No Black Magic ;)

**Comment by alexpopov** [comment]
Great,

I’m using Manuscript at work, but I’ll integrate the CGFloat branch into our nightly builds and see how it goes.

Thanks a lot for your work, your alignAllEdges call alone is something I’ve been meaning to write for ages.

—
 Alex Popov Jr. Lead Mobile Developer @ BitLit

**Comment by floriankrueger** [comment]
Please check the [hotfix/CGFloat](/floriankrueger/Manuscript/tree/hotfix/CGFloat). I'd love to hear what you think!
